// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  engine: 'classic',
  datasource: {
    url: 'postgresql://postgres:123456@localhost:5432/soindb?schema=public',
  },
});